### ISSUE TITLE
Regarding flyout.js

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1031]
I'm just wondering why this file is requested here:
https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/blocklyeditor/ploverConfig.js#L63

It isn't located in Blockly source code 😕

**Comment by ewpatton** [comment]
If you are looking at the Google master branch, you are correct. The Google team refactored the Flyout into multiple parts. When you use the git submodule update command it checks out the specific version we need (circa Feb 2017), which still has the singular flyout.js. I am working on an update that brings us back in line with the latest Blockly, but it will take some time because a number of internals that we rely on have changed.

**Comment by barreeeiroo** [comment]
So, why do I get this error?

```
BlocklyCompile:
     [java] Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /home/travis/build/barreeeiroo/Makeroid/appinventor/blocklyeditor/../lib/blockly/core/flyout.js (No such file or directory)
     [java] 	at org.plovr.JsSourceFile.getCode(JsSourceFile.java:24)
     [java] 	at org.plovr.AbstractJsInput.processProvidesAndRequires(AbstractJsInput.java:113)
     [java] 	at org.plovr.AbstractJsInput.getProvides(AbstractJsInput.java:83)
     [java] 	at org.plovr.Manifest.getProvideToSource(Manifest.java:214)
     [java] 	at org.plovr.Manifest.getInputsInCompilationOrder(Manifest.java:196)
     [java] 	at org.plovr.Manifest.getCompilerArguments(Manifest.java:177)
     [java] 	at org.plovr.CompileRequestHandler.compile(CompileRequestHandler.java:94)
     [java] 	at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:58)
     [java] 	at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:31)
     [java] 	at org.plovr.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:41)
     [java] 	at org.plovr.cli.Command.execute(Command.java:47)
     [java] 	at org.plovr.cli.Main.mainWithExitCode(Main.java:56)
     [java] 	at org.plovr.cli.Main.main(Main.java:30)
     [java] Caused by: java.io.FileNotFoundException: /home/travis/build/barreeeiroo/Makeroid/appinventor/blocklyeditor/../lib/blockly/core/flyout.js (No such file or directory)
     [java] 	at java.io.FileInputStream.open0(Native Method)
     [java] 	at java.io.FileInputStream.open(FileInputStream.java:195)
     [java] 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
     [java] 	at com.google.common.io.Files$1.getInput(Files.java:105)
     [java] 	at com.google.common.io.Files$1.getInput(Files.java:102)
     [java] 	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:249)
     [java] 	at com.google.common.io.Files.toByteArray(Files.java:197)
     [java] 	at com.google.common.io.Files.toString(Files.java:223)
     [java] 	at org.plovr.io.Files.toString(Files.java:12)
     [java] 	at org.plovr.JsSourceFile.getCode(JsSourceFile.java:22)
     [java] 	... 12 more
```

**Comment by barreeeiroo** [comment]
Nvm, it was caused because I was using the wrong branch 😅 

---

I'll keep this issue open, because I'm waiting for the Blockly update 👍

**Comment by ewpatton** [comment]
You can view the sources that get checked out as part of the `git submodule update` command on [out fork of Block]y(https://github.com/mit-cml/blockly/tree/mitmaster).

**Comment by kukudemajia** [comment]
This error still exists until now.
