### ISSUE TITLE
Build failed when use break in while.

### ISSUE THREAD

**Issue by p4ssw0rd** [mit-cml/appinventor-sources#1230]
#1180 

Tested in [http://ai2-test.appinventor.mit.edu](http://ai2-test.appinventor.mit.edu) 

![while](https://user-images.githubusercontent.com/3827464/39799448-d766df9a-5396-11e8-921a-7ce7e228cb09.png)

**Comment by ewpatton** [comment]
Confirmed. I also note that if I take the break block out of the loop, Kawa generates the following stack trace:

```
java.lang.Error: popType called with empty stack appinventor.ai_ewpatton.BreakTest.Screen1.Screen1$Initialize()java.lang.Object
at gnu.bytecode.CodeAttr.popType(CodeAttr.java:442)
at gnu.bytecode.CodeAttr.emitRawReturn(CodeAttr.java:2083)
at gnu.bytecode.CodeAttr.emitReturn(CodeAttr.java:2072)
at gnu.expr.LambdaExp.compileEnd(LambdaExp.java:544)
at gnu.expr.Compilation.generateBytecode(Compilation.java:2108)
at gnu.expr.Compilation.process(Compilation.java:1984)
at gnu.expr.ModuleInfo.loadByStages(ModuleInfo.java:330)
at gnu.expr.ModuleInfo.loadByStages(ModuleInfo.java:315)
at kawa.repl.compileFiles(repl.java:783)
at kawa.repl.processArgs(repl.java:412)
at kawa.repl.main(repl.java:827)
```

**Comment by ewpatton** [comment]
cc @jisqyv @halatmit I assume this is something to do with our use of call/cc.

**Comment by jisqyv** [comment]
Fixed by https://github.com/mit-cml/appinventor-sources/commit/70421e9b375f7ad9fbe9f579e3a621dfcf19dc5b

**Comment by p4ssw0rd** [comment]
Any blocks after while-break will cause the build to fail.

![failed](https://user-images.githubusercontent.com/3827464/41695276-f402710c-7540-11e8-9314-3d67b8d16a61.png)
