### ISSUE TITLE
Button - Error report

### ISSUE THREAD

**Issue by NmdOfficial** [mit-cml/appinventor-sources#1331]
We receive a lot of problems with the button clicks and dispatchevents:

`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next(HashMap.java:814)
       at com.google.appinventor.components.runtime.EventDispatcher.delegateDispatchEvent(EventDispatcher.java:219)
       at com.google.appinventor.components.runtime.EventDispatcher.dispatchEvent(EventDispatcher.java:198)
       at com.google.appinventor.components.runtime.Button.Click(Button.java:51)
       at com.google.appinventor.components.runtime.Button.click(Button.java:43)
       at com.google.appinventor.components.runtime.ButtonBase.onClick(ButtonBase.java:661)`

I figured it out that here:
https://github.com/mit-cml/appinventor-sources/blob/308f1f33e82a313ebd8ec0c5afaa10de30fb1678/appinventor/components/src/com/google/appinventor/components/runtime/Button.java#L43
and here
https://github.com/mit-cml/appinventor-sources/blob/308f1f33e82a313ebd8ec0c5afaa10de30fb1678/appinventor/components/src/com/google/appinventor/components/runtime/Button.java#L51

is a problem sometimes on a button click.

Is it not better to run the
`Click();` event in a runnable ?

I found on stackoverflow following.
https://stackoverflow.com/a/41620045

**Comment by ewpatton** [comment]
@NmdOfficial That is only an issue if `click` is called from a non-UI thread, which I don't believe it is in our sources, and according to the stack trace you included it is being called as part of the onClick event handler (UI thread). Instead, it is likely that another component is dispatching events not on the UI thread and causing the event handler map to be modified concurrently with the button click (e.g., Clock).

A more general approach might be to have `dispatchEvent` check to see if it is on the UI thread, and if not, call itself in a new runnable on the UI thread and log an error. For the App Inventor sources, any mistakes should be corrected, but we also cannot count on extension developers being right 100% of the time and so we should be defensive about how we handle threading in the future.
