### ISSUE TITLE
When i use my own account,Uncaught exception in Firebase runloop (2.5.0

### ISSUE THREAD

**Issue by GOTFire** [mit-cml/appinventor-sources#1404]
Hello
I can do same operation with the default firebase account but when i added my own account ı cant.

Please add your own firebase account and test it

Block photos and aia file
[https://drive.google.com/file/d/19ca8BdobzCgY-kWU39gY_y1jpxLykF6Y/view?usp=sharing](url)

[https://drive.google.com/file/d/15QusLT-VhKgqb2adbUI2RywY59rU5ZYS/view?usp=sharing](url)

`
java.lang.RuntimeException: Uncaught exception in Firebase runloop (2.5.0). Please report to support@firebase.com
 at com.firebase.client.android.AndroidPlatform$1$1.run(AndroidPlatform.java:49)
 at android.os.Handler.handleCallback(Handler.java:792)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6701)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.firebase.client.snapshot.ChildKey.equals(java.lang.Object)' on a null object reference
 at com.firebase.client.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:106)
 at com.firebase.client.core.SyncTree.removeEventRegistration(SyncTree.java:497)
 at com.firebase.client.core.SyncTree.removeEventRegistration(SyncTree.java:482)
 at com.firebase.client.core.Repo.removeEventCallback(Repo.java:391)
 at com.firebase.client.Query$2.run(Query.java:182)
 at com.firebase.client.utilities.DefaultRunLoop$1.run(DefaultRunLoop.java:54)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.firebase.client.snapshot.ChildKey.equals(java.lang.Object)' on a null object reference
 at com.firebase.client.core.CompoundHash$SimpleSizeSplitStrategy.shouldSplit(CompoundHash.java:59)
 at com.firebase.client.core.CompoundHash$CompoundHashBuilder.processLeaf(CompoundHash.java:128)
 at com.firebase.client.core.CompoundHash$CompoundHashBuilder.access$300(CompoundHash.java:64)
 at com.firebase.client.core.CompoundHash.processNode(CompoundHash.java:202)
 at com.firebase.client.core.CompoundHash.fromNode(CompoundHash.java:194)
 at com.firebase.client.core.CompoundHash.fromNode(CompoundHash.java:186)
 at com.firebase.client.core.SyncTree$ListenContainer.getCompoundHash(SyncTree.java:73)
 at com.firebase.client.core.PersistentConnection.sendListen(PersistentConnection.java:882)
 at com.firebase.client.core.PersistentConnection.listen(PersistentConnection.java:332)
 at com.firebase.client.core.Repo$3.startListening(Repo.java:117)
 at com.firebase.client.core.SyncTree$12.call(SyncTree.java:549)
 at com.firebase.client.core.SyncTree$12.call(SyncTree.java:497)
 at com.firebase.client.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:104)
 ... 11 more
`

**Comment by GOTFire** [comment]
I create this demo for cacth bug on my app.Its compiled app.Already installed on my phone.
  
  
  

  
  
  
  
  
>

**Comment by GOTFire** [comment]
I can confirm this bug.

**Comment by GOTFire** [comment]
I think there is same problem with this issue.
https://github.com/mit-cml/appinventor-sources/issues/1150

If we use append value and change project bucket at the same time its crash firebase.Hope you can fix it.
