### ISSUE TITLE
java.io.FileNotFoundException:  encoded_gs_key:L2dzL2Fw...

### ISSUE THREAD

**Issue by fsyzty** [mit-cml/appinventor-sources#2093]
Windows systems cannot create files with filenames containing ":".
For example: encoded_gs_key: L2dzL2FwcF9kZWZhdWx0X2J1Y2tldC80ODM3ODUxMTYyMjE0NDAwL2Fzc2V0cy9leHRlcm5hbF9jb21wcy9jby5jb20uZGVLzZFW2ZwWJF

严重: E:\ai2server\Ai2Server\DevServer\WEB-INF\appengine-generated\encoded_gs_key:L2dzL2FwcF9kZWZhdWx0X2J1Y2tldC81MDkyOTM3ODU5ODU4NDMyL2Fzc2V0cy8wLmpwZw (系统找不到指定的文件。): user=8740cc54-686d-47c4-ba9c-ac465f9f9e89, project=5092937859858432, **file=assets/0.jpg**
build.version=星期四, 1 一月 1970 08:00 CST
git.build.version=v181-71-g37db4a69-dirty
git.build.fingerprint=37db4a69324dbe0cbde82cc154fd1c7a85a72fa7

java.io.FileNotFoundException: E:\ai2server\Ai2Server\DevServer\WEB-INF\appengine-generated\encoded_gs_key:L2dzL2FwcF9kZWZhdWx0X2J1Y2tldC81MDkyOTM3ODU5ODU4NDMyL2Fzc2V0cy8wLmpwZw (系统找不到指定的文件。)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.google.appengine.api.blobstore.dev.FileBlobStorage$3.run(FileBlobStorage.java:68)
        at com.google.appengine.api.blobstore.dev.FileBlobStorage$3.run(FileBlobStorage.java:65)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.google.appengine.api.blobstore.dev.FileBlobStorage.fetchBlob(FileBlobStorage.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService$BlobStorageAdapter.fetchBlob(LocalRawGcsService.java:168)
        at com.google.appengine.tools.cloudstorage.dev.LocalRawGcsService.readObjectAsync(LocalRawGcsService.java:447)
        at com.google.appengine.tools.cloudstorage.SimpleGcsInputChannelImpl$1.call(SimpleGcsInputChannelImpl.java:91)
        at com.google.appengine.tools.cloudstorage.SimpleGcsInputChannelImpl$1.call(SimpleGcsInputChannelImpl.java:84)
        at com.google.appengine.tools.cloudstorage.RetryHelper.doRetry(RetryHelper.java:108)
        at com.google.appengine.tools.cloudstorage.RetryHelper.runWithRetries(RetryHelper.java:166)
        at com.google.appengine.tools.cloudstorage.RetryHelper.runWithRetries(RetryHelper.java:156)
        at com.google.appengine.tools.cloudstorage.SimpleGcsInputChannelImpl.read(SimpleGcsInputChannelImpl.java:84)
        at com.google.appinventor.server.storage.ObjectifyStorageIo.downloadRawFile(ObjectifyStorageIo.java:1870)
        at com.google.appinventor.server.FileExporterImpl.exportFile(FileExporterImpl.java:222)
        at com.google.appinventor.server.DownloadServlet.doGet(DownloadServlet.java:212)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1400)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
        at com.google.appinventor.server.OdeAuthFilter.doMyFilter(OdeAuthFilter.java:188)
        at com.google.appinventor.server.OdeAuthFilter.doFilter(OdeAuthFilter.java:133)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:134)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at com.google.appengine.tools.development.jetty9.StaticFileFilter.doFilter(StaticFileFilter.java:123)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
        at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
        at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at com.google.appengine.tools.development.DevAppServerRequestLogFilter.doFilter(DevAppServerRequestLogFilter.java:28)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
        at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:610)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:748)

2020-03-10 22:34:44.844:WARN:oejs.HttpChannel:qtp2107447833-16: handleException /ode/download/file/5092937859858432/assets/0.jpg java.io.FileNotFoundException: E:\ai2server\Ai2Server\DevServer\WEB-INF\appengine-generated\encoded_gs_key:L2dzL2FwcF9kZWZhdWx0X2J1Y2tldC81MDkyOTM3ODU5ODU4NDMyL2Fzc2V0cy8wLmpwZw (系统找不到指定的文件。)

**Comment by ewpatton** [comment]
This has nothing to do with App Inventor but rather it is an issue with how App Engine works. Make sure you're running the right version of Google App Engine. Also, if you've done an `ant clean` in a different window it will delete the directory where the currently running App Engine instance is expecting to write its files.
