### ISSUE TITLE
newblocks: App Inventor classic projects are currently not compatible with App Inventor newblocks

### ISSUE THREAD

**Issue by puravidaapps** [mit-cml/appinventor-sources#23]
I uploaded an old project from App Inventor classic to save some time to not have to redo the design and just to redo the blocks... Trying to package the project results in **Server error: could not save one or more files. Please try again later!** 

Packaging a very simple project created with App Inventor newblocks (e.g. just 1 button) works fine. Probably this error occurs only after uploading a project from App Inventor classic? 

I just tried it again with an empty project (only Screen1 without other components) from App Inventor classic: same error, which means, **App Inventor classic projects are currently not compatible with App Inventor newblocks**

---

**debug info:**
Clear
[INFO] AssetManager: formName = 5101733952880640_Screen1
[INFO] AssetManager: formName = 5101733952880640_Screen1
[INFO] AssetManager: formName = 5101733952880640_Screen1
[ERROR] Got exception: 500 The call failed on the server; see server log for details

---

**server log:**
INFO: Appstats available: /appstats/details?time=1368290004128
11.05.2013 10:33:24 com.google.apphosting.utils.jetty.AppEngineAuthentication$Ap
pEngineAuthenticator authenticate
INFO: Got /favicon.ico but no one was logged in, redirecting.
11.05.2013 10:33:24 com.google.appengine.tools.appstats.AppstatsFilter doFilter
INFO: Appstats available: /appstats/details?time=1368290004491
11.05.2013 10:33:24 com.google.appinventor.server.IdMap get
INFO: IdMap.get called for taifunbaer@gmail.com but no valid map exists.
11.05.2013 10:33:25 com.google.appengine.tools.appstats.AppstatsFilter doFilter
INFO: Appstats available: /appstats/details?time=1368290004970
//OK['T6UcJAh',[],0,7]
11.05.2013 10:33:30 com.google.appengine.api.datastore.dev.LocalDatastoreService
$PersistDatastore persist
INFO: Time to persist datastore: 63 ms
11.05.2013 10:34:00 com.google.appinventor.server.IdMap get
INFO: IdMap.get called for taifunbaer@gmail.com but no valid map exists.
11.05.2013 10:34:00 com.google.appengine.tools.development.ApiProxyLocalImpl log

SCHWERWIEGEND: javax.servlet.ServletContext log: Exception while dispatching inc
oming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstr
act long com.google.appinventor.shared.rpc.project.ProjectService.save(java.util
.List)' threw an unexpected exception: java.lang.IllegalStateException
        at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:
389)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:5
79)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(Remot
eServiceServlet.java:208)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(Remot
eServiceServlet.java:248)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(Ab
stractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1166)
        at com.google.appinventor.server.OdeAuthFilter.doMyFilter(Unknown Source
)
        at com.google.appinventor.server.OdeAuthFilter.doFilter(Unknown Source)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsF
ilter.java:141)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocke
tFilter.java:74)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at com.google.appengine.tools.development.ResponseRewriterFilter.doFilte
r(ResponseRewriterFilter.java:123)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at com.google.appengine.tools.development.HeaderVerificationFilter.doFil
ter(HeaderVerificationFilter.java:34)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(Serve
BlobFilter.java:63)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter
(TransactionCleanupFilter.java:43)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at com.google.appengine.tools.development.StaticFileFilter.doFilter(Stat
icFileFilter.java:125)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at com.google.appengine.tools.development.DevAppServerServersFilter.doDi
rectRequest(DevAppServerServersFilter.java:369)
        at com.google.appengine.tools.development.DevAppServerServersFilter.doDi
rectServerRequest(DevAppServerServersFilter.java:352)
        at com.google.appengine.tools.development.DevAppServerServersFilter.doFi
lter(DevAppServerServersFilter.java:115)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
88)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

```
    at com.google.appengine.tools.development.DevAppEngineWebAppContext.hand
```

le(DevAppEngineWebAppContext.java:94)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at com.google.appengine.tools.development.JettyContainerService$ApiProxy
Handler.handle(JettyContainerService.java:421)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnectio
n.java:938)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.ja
va:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.j
ava:582)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:13
3)
        at com.google.appinventor.server.storage.ObjectifyStorageIo$31.run(Unkno
wn Source)
        at com.google.appinventor.server.storage.ObjectifyStorageIo.runJobWithRe
tries(Unknown Source)
        at com.google.appinventor.server.storage.ObjectifyStorageIo.uploadRawFil
e(Unknown Source)
        at com.google.appinventor.server.storage.ObjectifyStorageIo.uploadFile(U
nknown Source)
        at com.google.appinventor.server.project.CommonProjectService.save(Unkno
wn Source)
        at com.google.appinventor.server.ProjectServiceImpl.save(Unknown Source)

```
    at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(R
```

untime.java:115)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:5
61)
        ... 45 more

11.05.2013 10:34:00 com.google.appengine.tools.appstats.AppstatsFilter doFilter
INFO: Appstats available: /appstats/details?time=1368290040090

**Comment by tcsiwula** [comment]
+1
