### ISSUE TITLE
Vagrant w/ libvirt

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [mit-cml/appinventor-sources#2369]
Hey there!

I was trying to run a local version of this app using vagrant and libvirt. But I only managed to go so far. Any pointers would be much appreciated.

Here's the change that I have made to the Vagrantfile (so far):
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.boot_timeout = 400

  config.vm.provider "virtualbox" do |v|
    v.name = "ForAppinventor2-bionic64"
    v.memory = "4096"
    v.customize ["modifyvm", :id, "--usb", "on"]
    # fix for slow network
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.vm.provider :libvirt do |libvirt|
    config.vm.box = "generic/ubuntu1804"
    libvirt.socket = "/run/user/1000/libvirt/libvirt-sock"
    libvirt.uri = "qemu:///session"
  end

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.network :forwarded_port, guest: 8888, host: 8888
  config.vm.network :forwarded_port, guest: 9876, host: 9876
  config.vm.network :forwarded_port, guest: 9990, host: 9990

end
```
And this is the error I'm currently stuck at:
```
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'generic/ubuntu1804' version '3.1.22' is up to date...
==> default: Uploading base box image as volume into libvirt storage...
/usr/lib/ruby/vendor_ruby/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virStorageVolCreateXML failed: cannot chown $HOME/.local/share/libvirt/images/generic-VAGRANTSLASH-ubuntu1804_vagrant_box_image_3.1.22.img to (0, 0): Operation not permitted (Libvirt::Error)
	from /usr/lib/ruby/vendor_ruby/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume'
	from /usr/lib/ruby/vendor_ruby/fog/libvirt/models/compute/volume.rb:42:in `save'
	from /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:50:in `create'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:107:in `block in call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:65:in `synchronize'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:65:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_storage_pool.rb:57:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/box_check_outdated.rb:84:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/machine.rb:238:in `action_raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/machine.rb:209:in `block in action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:613:in `lock'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

I would appreciate any pointers regarding the matter. Thank you.

**Comment by peanutbutterandcrackers** [comment]
Update:

The following change fixes this issue:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.boot_timeout = 400

  config.vm.provider "virtualbox" do |v|
    v.name = "ForAppinventor2-bionic64"
    v.memory = "4096"
    v.customize ["modifyvm", :id, "--usb", "on"]
    # fix for slow network
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.vm.provider :libvirt do |libvirt|
    config.vm.box = "generic/ubuntu1804"
    libvirt.qemu_use_session = true
    libvirt.socket = "/run/user/1000/libvirt/libvirt-sock"
    libvirt.uri = "qemu:///session"
  end

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.network :forwarded_port, guest: 8888, host: 8888
  config.vm.network :forwarded_port, guest: 9876, host: 9876
  config.vm.network :forwarded_port, guest: 9990, host: 9990

end
```

However, I have ran into further issues which aren't related to this.

I'm leaving this here for anyone who might want to run appinventor locally w/ libvirt.

**Comment by ewpatton** [comment]
@peanutbutterandcrackers You may want to consider submitting these changes as a PR so it will be easier for folks in the future rather than hiding it in a closed issue.

**Comment by peanutbutterandcrackers** [comment]
@ewpatton - I am afraid I might need to tweak a few things before this is PR-worthy. I will submit a PR as soon as I am done figuring the current (my-machine-specific, I'm sure) issue that I'm struggling with.
