### ISSUE TITLE
Broken symlinks

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [mit-cml/appinventor-sources#2375]
I am [trying to get a locally hosted app inventor running on my machine w/ libvirt](https://github.com/mit-cml/appinventor-sources/issues/2369) instead of virtualbox. And because [the normal shared folder is not working properly](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1201), I had to [switch to rsync](https://github.com/vagrant-libvirt/vagrant-libvirt#synced-folders) instead of NFS for sharing folders w/ the host machine. However, in doing so I found that there are a few broken symlinks in the source tree.

I just want to report it here for the consideration of the maintainers to confirm whether or not this is an issue. When I manually told rysync to not copy symlinks, the virtual box did run but went on to fail at the `ant` step: for blockly compilation. So I was wondering if these broken symlinks might have something to do with it.

```
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'generic/ubuntu1804' is up to date...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              appinventor-sources_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default: 
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            2048M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          generic/ubuntu1804
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/appinventor-sources_default.img (128G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        256
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Forwarding ports...
==> default: 8888 (guest) => 8888 (host) (adapter eth0)
==> default: 9876 (guest) => 9876 (host) (adapter eth0)
==> default: 9990 (guest) => 9990 (host) (adapter eth0)
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: $HOME/.bin/appinventor-sources/ => /vagrant
#<Thread:0x00005593d9749240@/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/synced_folders/rsync/helper.rb:200:in `rsync_single': There was an error when attempting to rsync a synced folder. (Vagrant::Errors::RSyncError)
Please inspect the error message below for more info.

Host path: $HOME/.bin/appinventor-sources/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 22 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/tmp/ssh.581 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '$HOME/.bin/appinventor-sources/.vagrant/machines/default/libvirt/private_key'" "--exclude" ".vagrant/" "$HOME/.bin/appinventor-sources/" "vagrant@192.168.121.110:/vagrant"
Error: symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/js-yaml"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/he"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/mocha"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/esparse"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/esvalidate"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/_mocha"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/mocha/node_modules/.bin/mkdirp"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/mocha/node_modules/.bin/which"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/node-environment-flags/node_modules/.bin/semver"
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/synced_folders/rsync/synced_folder.rb:48:in `block in enable'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/synced_folders/rsync/synced_folder.rb:47:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/synced_folders/rsync/synced_folder.rb:47:in `enable'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/synced_folders.rb:93:in `block in call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/synced_folders.rb:90:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/synced_folders.rb:90:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/create_domain.rb:317:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/create_domain_volume.rb:82:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_box_image.rb:113:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_storage_pool.rb:52:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_check_outdated.rb:79:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: $HOME/.bin/appinventor-sources/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 22 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/tmp/ssh.581 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '$HOME/.bin/appinventor-sources/.vagrant/machines/default/libvirt/private_key'" "--exclude" ".vagrant/" "$HOME/.bin/appinventor-sources/" "vagrant@192.168.121.110:/vagrant"
Error: symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/js-yaml"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/he"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/mocha"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/esparse"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/esvalidate"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/.bin/_mocha"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/mocha/node_modules/.bin/mkdirp"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/mocha/node_modules/.bin/which"
symlink has no referent: "$HOME/.bin/appinventor-sources/appinventor/node_modules/node-environment-flags/node_modules/.bin/semver"
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

**Comment by ewpatton** [comment]
You should be able to ignore these warnings. If it's a particular concern, try running `npm install` in your virtual machine to update them for your platform to see if that helps. The node modules are only used for running some of the unit tests and aren't critical for regular development work.

**Comment by peanutbutterandcrackers** [comment]
I see. Thank you very much! I will try it out right away (and close this issue afterwards)

**Comment by peanutbutterandcrackers** [comment]
Done. This issue does not affect running a local version of app inventor w/ vagrant/libvirt.
