### ISSUE TITLE
ant: BlocklyCompile failure

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [mit-cml/appinventor-sources#2376]
I'm following [these instructions](https://github.com/mit-cml/appinventor-sources#setup-instructions-vagrant) to [run appinventor w/ vagrant/libvirt](https://github.com/mit-cml/appinventor-sources/issues/2369). I went ahead, `vagrant ssh`-ed, and ran `ant`, and it fails at BlocklyCompile with the following errors:
```
Buildfile: /vagrant/appinventor/build.xml

all:

init:

MakeWarLibsDir:

common_CommonUtils:

init:

CommonUtils:

common_CommonVersion:

init:

CommonVersion:

components_CommonConstants:

init:

CommonConstants:

WarLibs:

AiSharedLib:

AiServerLib:

components_AndroidRuntime:

common_CommonVersion:

init:

CommonVersion:

init:

HtmlEntities:

Barcode:

CopyComponentLibraries:

common_CommonUtils:

init:

CommonUtils:

CommonConstants:

AnnotationProcessors:

AndroidRuntime.uptodate:

AndroidRuntime:

AiClientLib:

AiRebindLib:

blocklyeditor_BlocklyTranslationGenerator:

CheckBlocklyTranslations:

init:

CheckBlocklyCompile:

BlocklyCompile:
     [java] Exception in thread "main" java.lang.IllegalArgumentException: File not found at: /vagrant/appinventor/blocklyeditor/../lib/closure-library/closure/goog
     [java] 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
     [java] 	at org.plovr.Manifest.getInputs(Manifest.java:393)
     [java] 	at org.plovr.Manifest.getFiles(Manifest.java:369)
     [java] 	at org.plovr.Manifest.getFiles(Manifest.java:363)
     [java] 	at org.plovr.Manifest.getAllDependencies(Manifest.java:324)
     [java] 	at org.plovr.Manifest.getInputsInCompilationOrder(Manifest.java:193)
     [java] 	at org.plovr.Manifest.getCompilerArguments(Manifest.java:177)
     [java] 	at org.plovr.CompileRequestHandler.compile(CompileRequestHandler.java:94)
     [java] 	at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:58)
     [java] 	at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:31)
     [java] 	at org.plovr.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:41)
     [java] 	at org.plovr.cli.Command.execute(Command.java:47)
     [java] 	at org.plovr.cli.Main.mainWithExitCode(Main.java:56)
     [java] 	at org.plovr.cli.Main.main(Main.java:30)

BUILD FAILED
/vagrant/appinventor/build.xml:16: The following error occurred while executing this line:
/vagrant/appinventor/build-common.xml:299: The following error occurred while executing this line:
/vagrant/appinventor/blocklyeditor/build.xml:111: Java returned: 1

Total time: 6 seconds
```

I am certain that this is not enough information. Please do give me a few pointers regarding the matter. Thank you!

**Comment by peanutbutterandcrackers** [comment]
Ah! Here!

(so, basically `ant` is like `make`)

More info (output of `ant BlocklyTest`):
```
Buildfile: /vagrant/appinventor/build.xml

BlocklyTest:

components_AndroidRuntime:

common_CommonVersion:

init:

CommonVersion:

init:

HtmlEntities:

Barcode:

CopyComponentLibraries:

common_CommonUtils:

init:

CommonUtils:

CommonConstants:

AnnotationProcessors:

AndroidRuntime.uptodate:

AndroidRuntime:

common_CommonTestUtils:

init:

CommonTestUtils:

BlocklyTestbed:

BUILD FAILED
/vagrant/appinventor/build.xml:88: The following error occurred while executing this line:
/vagrant/appinventor/blocklyeditor/build.xml:140: /vagrant/appinventor/lib/blockly/media does not exist.

Total time: 2 seconds
```

**Comment by peanutbutterandcrackers** [comment]
Wait... I think I missed some `git submodule`-related instruction. Looking at it again.

**Comment by peanutbutterandcrackers** [comment]
Okay. Done. I'd missed a `git submodule` instruction.

**Comment by Professionalrix** [comment]
BlocklyCompile:

BlocklyTranslationGenerator:

BUILD FAILED
C:\Users\Narender Singh\appinventor-sources\appinventor\build.xml:50: The following error occurred while executing this line:
C:\Users\Narender Singh\appinventor-sources\appinventor\build-common.xml:299: The following error occurred while executing this line:
C:\Users\Narender Singh\appinventor-sources\appinventor\blocklyeditor\build.xml:95: java.nio.file.NoSuchFileException: Singh\appinventor-sources\appinventor\blocklyeditor\src\msg\ai_blockly\en.json
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
at java.nio.file.Files.newByteChannel(Files.java:361)
at java.nio.file.Files.newByteChannel(Files.java:407)
at java.nio.file.Files.readAllBytes(Files.java:3152)
at msg.BlocklyTranslationGenerator.main(BlocklyTranslationGenerator.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:218)
at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
at org.apache.tools.ant.taskdefs.Java.run(Java.java:861)
at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
at org.apache.tools.ant.Main.runBuild(Main.java:827)
at org.apache.tools.ant.Main.startAnt(Main.java:223)
at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

**Comment by josmas** [comment]
Seems like there is a space within your name and surname. Java doesn't like that.
