### ISSUE TITLE
Build failed with the latest version of the source code

### ISSUE THREAD

**Issue by code-Former** [mit-cml/appinventor-sources#2480]
I cloned the repo and here are my dependencies:
- Vagrant 2.2.15
- Apache Ant(TM) version 1.10.5

I followed the instructions in the README file, running the command `ant` gave me the following error:

```bash
BlocklyCompile:
     [java] Exception in thread "main" java.lang.IllegalArgumentException: File not found at: /vagrant/appinventor/blocklyeditor/../lib/closure-library/closure/goog
     [java]     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
     [java]     at org.plovr.Manifest.getInputs(Manifest.java:393)
     [java]     at org.plovr.Manifest.getFiles(Manifest.java:369)
     [java]     at org.plovr.Manifest.getFiles(Manifest.java:363)
     [java]     at org.plovr.Manifest.getAllDependencies(Manifest.java:324)
     [java]     at org.plovr.Manifest.getInputsInCompilationOrder(Manifest.java:193)
     [java]     at org.plovr.Manifest.getCompilerArguments(Manifest.java:177)
     [java]     at org.plovr.CompileRequestHandler.compile(CompileRequestHandler.java:94)
     [java]     at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:58)
     [java]     at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:31)
     [java]     at org.plovr.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:41)
     [java]     at org.plovr.cli.Command.execute(Command.java:47)
     [java]     at org.plovr.cli.Main.mainWithExitCode(Main.java:56)
     [java]     at org.plovr.cli.Main.main(Main.java:30)

BUILD FAILED
/vagrant/appinventor/build.xml:16: The following error occurred while executing this line:
/vagrant/appinventor/build-common.xml:299: The following error occurred while executing this line:
/vagrant/appinventor/blocklyeditor/build.xml:118: Java returned: 1
```

This there something that I am missing?
Thanks in advance

**Comment by preetvadaliya** [comment]
@code-Former  please ask your question in the open-source community http://community.appinventor.mit.edu/
