### ISSUE TITLE
Connect -->USB  AI2 Companion Can't preview, only white screen

### ISSUE THREAD

**Issue by fsyzty** [mit-cml/appinventor-sources#2667]
AI2 Companion 2.62u
v185a-169-g65e926ce

Uncaught TypeError: Cannot read properties of undefined (reading 'processRetvals')
    at XMLHttpRequest.conn.onreadystatechange (ode-0.js:325026:21)

Uncaught TypeError: Cannot read properties of undefined (reading 'processRetvals')
    at XMLHttpRequest.rxhr.onreadystatechange (ode-0.js:325065:46)

**Comment by fsyzty** [comment]
Comparing the two files in https://github.com/mit-cml/appinventor-sources/commit/65e926ce5ff4b9bd029e50907fe052639e55f479, it is found that the Blockly.ReplMgr.loadExtensions of replmgr.js can be displayed normally after restoring.

```
Blockly.ReplMgr.loadExtensions = function() {
    var rs = top.ReplState;
 if (top.usewebrtc) {
    // Need to trigger the loading of extensions here
    rs.state = Blockly.ReplMgr.rsState.EXTENSIONS;
    var extensionJson = JSON.stringify(top.AssetManager_getExtensions());
    extensionJson = Blockly.Yail.quotifyForREPL(extensionJson);
    var yailstring = "(AssetFetcher:loadExtensions " +
        extensionJson + ")";
    console.log("Blockly.ReplMgr.loadExtensions: Yail = " + yailstring);
    this.putYail.putAsset(yailstring);
} else {
        rs.state = Blockly.ReplMgr.rsState.EXTENSIONS;
        var xmlhttp = goog.net.XmlHttp();
        var encoder = new goog.Uri.QueryData();
        encoder.add('extensions', JSON.stringify(top.AssetManager_getExtensions()));
        xmlhttp.open('POST', rs.extensionurl, true);
        xmlhttp.onreadystatechange = function() {
            /* Older companions do not support ReplMgr providing an extension list. This check below
             * handles older companions as well as new companions so that we don't break old clients.
             */
            if (xmlhttp.readyState === 4 && (this.status === 200 || this.status === 404 || !this.status)) {
                rs.state = Blockly.ReplMgr.rsState.CONNECTED;
                Blockly.mainWorkspace.fireChangeListener(new AI.Events.CompanionConnect());
            } else if (xmlhttp.readyState === 4) {
                rs.state = Blockly.ReplMgr.rsState.IDLE;
                top.BlocklyPanel_indicateDisconnect();
            }
        };
        xmlhttp.send(encoder.toString());
    }
};

```

```
rs.baseurl = 'http://127.0.0.1:8001/';
rs.extensionurl = rs.baseurl + '_extensions';
```

```
 rs.baseurl = 'http://' + json.ipaddr + ':8001/';
 rs.extensionurl = rs.baseurl + '_extensions';
```

**Comment by fsyzty** [comment]
ok
