### ISSUE TITLE
Ant Build Error: Unable to make protected final...

### ISSUE THREAD

**Issue by XomaDev** [mit-cml/appinventor-sources#2770]
An error while compiling ant

When I run the command `ant`, I face a weird error that I have never faced before. I dont know why it happened.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [x] Other

I have done no changes at all, I installed the sub modules, created the auth key and ran the ant command.

```java
kumaraswamy@kumaraswamy:~/Documents/Baxolino/appinventor-sources/appinventor$ ant
Buildfile: /home/kumaraswamy/Documents/Baxolino/appinventor-sources/appinventor/build.xml

all:

init:

MakeWarLibsDir:

common_CommonUtils:

init:

CommonUtils:

common_CommonVersion:

init:

CommonVersion:

components_CommonConstants:

init:

CommonConstants:

WarLibs:

AiSharedLib:

AiServerLib:

components_AndroidRuntime:

common_CommonVersion:

init:

CommonVersion:

init:

HtmlEntities:

Barcode:

CopyComponentLibraries:

common_CommonUtils:

init:

CommonUtils:

CommonConstants:

AnnotationProcessors:

AndroidRuntime.uptodate:

AndroidRuntime:

AiClientLib:

AiRebindLib:

blocklyeditor_BlocklyTranslationGenerator:

CheckBlocklyTranslations:

init:

CheckBlocklyCompile:

BlocklyCompile:
     [java] Exception in thread "main" java.lang.ExceptionInInitializerError
     [java] 	at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:58)
     [java] 	at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:31)
     [java] 	at org.plovr.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:41)
     [java] 	at org.plovr.cli.Command.execute(Command.java:47)
     [java] 	at org.plovr.cli.Main.mainWithExitCode(Main.java:56)
     [java] 	at org.plovr.cli.Main.main(Main.java:30)
     [java] Caused by: com.google.inject.internal.util.$ComputationException: java.lang.ExceptionInInitializerError
     [java] 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
     [java] 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
     [java] 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
     [java] 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
     [java] 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
     [java] 	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:507)
     [java] 	at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:159)
     [java] 	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44)
     [java] 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
     [java] 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
     [java] 	at com.google.inject.Guice.createInjector(Guice.java:95)
     [java] 	at com.google.inject.Guice.createInjector(Guice.java:72)
     [java] 	at com.google.inject.Guice.createInjector(Guice.java:62)
     [java] 	at com.google.template.soy.GuiceInitializer.initializeIfNecessary(GuiceInitializer.java:55)
     [java] 	at com.google.template.soy.SoyFileSet$Builder.<init>(SoyFileSet.java:141)
     [java] 	at com.google.template.soy.SoyFileSet$Builder.<init>(SoyFileSet.java:125)
     [java] 	at org.plovr.CompileRequestHandler.<clinit>(CompileRequestHandler.java:33)
     [java] 	... 6 more
     [java] Caused by: java.lang.ExceptionInInitializerError
     [java] 	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
     [java] 	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
     [java] 	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
     [java] 	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
     [java] 	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
     [java] 	at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:207)
     [java] 	at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:53)
     [java] 	at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:153)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:89)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
     [java] 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
     [java] 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
     [java] 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
     [java] 	... 23 more
     [java] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4a684241
     [java] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
     [java] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
     [java] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
     [java] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
     [java] 	at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
     [java] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
     [java] 	at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
     [java] 	... 37 more

BUILD FAILED
/home/kumaraswamy/Documents/Baxolino/appinventor-sources/appinventor/build.xml:16: The following error occurred while executing this line:
/home/kumaraswamy/Documents/Baxolino/appinventor-sources/appinventor/build-common.xml:301: The following error occurred while executing this line:
/home/kumaraswamy/Documents/Baxolino/appinventor-sources/appinventor/blocklyeditor/build.xml:120: Java returned: 1

Total time: 1 second
kumaraswamy@kumaraswamy:~/Documents/Baxolino/appinventor-sources/appinventor$ 
```

## Java versions

I have Java versions correctly installed, and they are 8:

```
kumaraswamy@kumaraswamy:~/Documents/Baxolino/appinventor-sources/appinventor$ java -version && javac -version
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-8u342-b07-0ubuntu1~22.04-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)
javac 1.8.0_342
kumaraswamy@kumaraswamy:~/Documents/Baxolino/appinventor-sources/appinventor$
```

**Comment by ewpatton** [comment]
@XomaDev If you're installing `ant` via brew, it's actually a shell script that sets JAVA_HOME to be a newer JDK and then invokes ant, which will result in that error. You can work around this either by editing the script or by downloading the binaries from the Apache Ant website and configuring that version to be on your PATH before the homebrew version.

**Comment by ewpatton** [comment]
Given the lack of activity I am assuming the issue has been resolved.
