### ISSUE TITLE
Installation Error:  File not found at: /appinventor/blocklyeditor/../lib/closure-library/closure/goog

### ISSUE THREAD

**Issue by DavidWisdom** [mit-cml/appinventor-sources#3009]
I'm getting a "BUILD FAILED" error message when I try to run the ant command during installation.

```text
BlocklyCompile:
     [java] Exception in thread "main" java.lang.IllegalArgumentException: File not found at: /home/eric/src/appinventor-sources/appinventor/blocklyeditor/../lib/closure-library/closure/goog
     [java]     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
     [java]     at org.plovr.Manifest.getInputs(Manifest.java:393)
     [java]     at org.plovr.Manifest.getFiles(Manifest.java:369)
     [java]     at org.plovr.Manifest.getFiles(Manifest.java:363)
     [java]     at org.plovr.Manifest.getAllDependencies(Manifest.java:324)
     [java]     at org.plovr.Manifest.getInputsInCompilationOrder(Manifest.java:193)
     [java]     at org.plovr.Manifest.getCompilerArguments(Manifest.java:177)
     [java]     at org.plovr.CompileRequestHandler.compile(CompileRequestHandler.java:94)
     [java]     at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:58)
     [java]     at org.plovr.cli.BuildCommand.runCommandWithOptions(BuildCommand.java:31)
     [java]     at org.plovr.cli.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:41)
     [java]     at org.plovr.cli.Command.execute(Command.java:47)
     [java]     at org.plovr.cli.Main.mainWithExitCode(Main.java:56)
     [java]     at org.plovr.cli.Main.main(Main.java:30)

BUILD FAILED
/home/eric/src/appinventor-sources/appinventor/build.xml:16: The following error occurred while executing this line:
/home/eric/src/appinventor-sources/appinventor/build-common.xml:301: The following error occurred while executing this line:
/home/eric/src/appinventor-sources/appinventor/blocklyeditor/build.xml:120: Java returned: 1

Total time: 10 seconds
```
![image](https://github.com/mit-cml/appinventor-sources/assets/88563609/32644849-3ada-4207-93e3-74da79d03bda)
![image](https://github.com/mit-cml/appinventor-sources/assets/88563609/0fc6a077-e682-43f2-b06d-403aa545a19a)

Would anyone be able to provide a solution for resolving this error? Thank you.

**Comment by josmas** [comment]
hey @DavidWisdom have you followed the install instruction for submodules? https://github.com/mit-cml/appinventor-sources#checkout-dependencies

**Comment by DavidWisdom** [comment]
I forgot to check out dependencies. Thank you.
