### ISSUE TITLE
Cannot remove pie chart entries on Android

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#3262]
**Describe the bug**

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Projects Explorer
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Trying to remove an existing entry in the pie chart gives the following error:

```
java.lang.NumberFormatException: For input string: "cherry"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
at java.lang.Float.parseFloat(Float.java:451)
at com.google.appinventor.components.runtime.ChartData2D$2.run(ChartData2D.java:120) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
at java.lang.Thread.run(Thread.java:919) 
```

**Steps to reproduce**

1. Add a Chart and ChartData2D to a project
2. Populate the ChartData2D with some values via ElementsFromString, e.g., "apple,2,blueberry,3,cherry,5
3. Add a ChartData2D.RemoveEntry block to the block workspace to remove ("cherry",5) and use "Do It" to perform the behavior

**Comment by d1vyanshu-kumar** [comment]
Hello @ewpatton,
I'm a new MIT App Inventor contributor and tried to replicate the issue. I followed the steps mentioned, but when I click on "Do It," the option is disabled. I'm not sure why this is happening. I can share a screenshot if that helps

<img width="1440" alt="Screenshot 2024-12-10 at 2 08 20 PM" src="https://github.com/user-attachments/assets/1dadad17-a70f-49f8-8901-3550e75eaa69">
<img width="1440" alt="Screenshot 2024-12-10 at 2 08 49 PM" src="https://github.com/user-attachments/assets/af9b932d-906f-40a6-8a50-f55f26c766db">

**Comment by SusanRatiLane** [comment]
> Hello @ewpatton, I'm a new MIT App Inventor contributor and tried to replicate the issue. I followed the steps mentioned, but when I click on "Do It," the option is disabled. I'm not sure why this is happening. 

Do you have the app loaded on the Companion, either on a physical device or emulator? Do It requires access to the Companion to work.

**Comment by ShreyashN16** [comment]
Hello everyone,

I wanted to provide additional clarification and confirm the steps I followed:

I replicated the issue using the latest version of the Companion on an Android device.
After populating ChartData2D with ElementsFromString and attempting to remove an entry (e.g., "cherry", 5), the app throws a NumberFormatException error.
It appears that the issue stems from the label ("cherry") being parsed as a numeric value.
Suggested Fix:

Update the ChartData2D.RemoveEntry logic to correctly distinguish between numeric values and string labels.
Implement a safeguard to prevent non-numeric labels from being parsed as floats.
Let me know if there's any additional debugging or testing you'd like me to perform.

Thank you!

**Comment by ewpatton** [comment]
@ShreyashN16 That sounds roughly correct but in theory people may still want to be able to use numeric labels, they will just have to be converted to strings first.

**Comment by ShreyashN16** [comment]
@ewpatton 
You're absolutely right—numeric labels can be useful, especially when dealing with datasets. If the system mandates string labels, users can convert numeric labels to strings before adding them to the chart. For instance, 
in Java:
```java
int numericLabel = 123;
String label = Integer.toString(numericLabel;
// Add the label to the chart
``` 
This approach maintains flexibility while conforming to the current requirements. It might also be worth considering an enhancement where the system internally handles such conversions for better usability.

**Comment by cindyloo** [comment]
reproduced:
![Image](https://github.com/user-attachments/assets/15310977-a41e-4a8c-b80a-a3bab6c649c5)

**Comment by ShreyashN16** [comment]
Thank you for the clarification, @ewpatton. I understand that numeric
labels should still be supported but need to be converted to strings first.
I'll look into ensuring that both numeric and string labels are handled
properly while preventing unintended NumberFormatException errors.

Would it be preferable to enforce this conversion automatically within the
ChartData2D component, or should we require users to explicitly format
their inputs before passing them?

Also, I would love to contribute more to MIT App Inventor beyond this
issue. If you could encourage me by adding me to your team for GSoC 2025, I
would be highly motivated to work on more features and improvements.
Looking forward to your thoughts!

**Comment by cindyloo** [comment]
updating ChartData2D to work with both strings and numbers for the x value (coordinate or label).
Charts other than PieChart would also need some kind of initialization provision as PieChart has
```
    public PieEntry(float value, String label) {
        super(0.0F, value);
        this.label = label;
    }
```

**Comment by cindyloo** [comment]
updated code will handle a NumberFormatException, calculate the index value of the label-as-x, and pass that again to the 'dataModel' `addEntryFromTuple` or `getEntryFromTuple`

**Comment by cindyloo** [comment]
assume that the index from Labels 
```
 YailList labelList = container.Labels();
 int indexList = labelList.indexOf(x);
```

is not necessarily the same index as what may come back from 
```
Entry currEntry = dataModel.getEntryFromTuple(pairFromLabel);
            int indexFromFind = dataModel.findEntryIndex(currEntry);
```

**Comment by cindyloo** [comment]
tested with labels and with numerical x values across all chart types

**Comment by sreeja2007** [comment]
Hello ,

I’m a new contributor to MIT App Inventor and I’ve gone through this issue and the related discussion. I understand the problem and would like to work on it.

If the issue is still open, could you please assign it to me?  
Thank you!

**Comment by ewpatton** [comment]
Fixed by #3384
