### ISSUE TITLE
Canvas Camera Live Feed

### ISSUE THREAD

**Issue by thequixotic** [mit-cml/appinventor-sources#363]
https://github.com/josmas/OurBricks_AppInventor/wiki/Live-Feed-Design

Changed the Canvas Component. 
Did some mutation to CanvasView to make it surface view. 

Drawing order :
Camera Feed (optional) // drawn only if CameraFeed is set to true
Background Color / Image
Canvas Bitmap
Sprites (in order of their addition)

Maybe suggestions on the new properties to be added.
Right now .. 
CameraFeed boolean
CameraUseFront boolean 
.. maybe Some camera properties also maybe like exposure, balance etc. found in Camera Parameters (http://developer.android.com/reference/android/hardware/Camera.Parameters.html)

Came up with this. Test APK https://drive.google.com/file/d/0B6TjsdbpeaqcMXVFQVlDWk5XaGs/view?usp=sharing
Is this what is expected from a live feed ?

@josmas @jisqyv

**Comment by halatmit** [comment]
I tried loading the apk and running it and it crashed with

E/QCameraHWI_Parm( 1566): Invalid preview size requested: 320x300
D/AndroidRuntime(30434): Shutting down VM
E/AndroidRuntime(30434): FATAL EXCEPTION: main
E/AndroidRuntime(30434): Process: appinventor.ai_admin.canvasCamera, PID: 30434
E/AndroidRuntime(30434): java.lang.RuntimeException: setParameters failed
E/AndroidRuntime(30434): 	at android.hardware.Camera.native_setParameters(Native Method)

In any case, when implementing this, remember that we need to support phones down to Gingerbread.

Also  Mark Sherman is thinking about the camera, and this might interact.
@marksherman

**Comment by thequixotic** [comment]
yea the that preview size is not supported for your camera. I ll fix that asap. I need to set supported preview sizes.

Right now the preview size blindly takes the Canvas size. Entire Canvas is used for preview. Unfortunately not all cameras support all preview size. 

@josmas 
What do you suggest to do if the Canvas size is not a supported camera preview size ? 
use only a part of the canvas for preview ? or force change the most suitable canvas size .

**Comment by thequixotic** [comment]
@halatmit  
I tried now previewing at supported preview sizes only. 
what device do you use ? 
New APK link https://drive.google.com/open?id=0B6TjsdbpeaqcMXVFQVlDWk5XaGs&authuser=0

**Comment by halatmit** [comment]
I have a Nexus 4 running android 5.1



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by thequixotic** [comment]
Does the new APK work? 
https://drive.google.com/open?id=0B6TjsdbpeaqcMXVFQVlDWk5XaGs&authuser=0

**Comment by halatmit** [comment]
This works better.   Nice!!
One problem is that when i try to take a picture, except for the very first time, I get an error "can't connect to camera" (logcat below).   When you fix this up for merging into App Inventor, make sure it works back to Gingerbread, or at least degrades gracefully.    Also check what's going on with pull request #335, which is talking about changing the camera component.
@marksherman 

Logcat excerpt:

V/CAM_TexViewHelper( 5857): onLayoutChange
V/CAM_TexViewHelper( 5857): updateTransform
V/CAM_TexViewHelper( 5857): updateTransform
V/CAM_CameraAppUI( 5857): SurfaceTexture is available
D/CAM_StateMachine( 5857): Process event : com.android.camera.captureintent.event.EventOnSurfaceTextureAvailable@132582d5
D/CAM_StateMachine( 5857): Change state : com.android.camera.captureintent.state.StateForeground@2f1aa430 => com.android.camera.captureintent.state.StateForegroundWithSurfaceTexture@1a93caea
D/CAM_Camera2OneCamMgr( 5857): Getting First BACK Camera
D/CAM_StateMachine( 5857): Forward state : com.android.camera.captureintent.state.StateForegroundWithSurfaceTexture@1a93caea => com.android.camera.captureintent.state.StateOpeningCamera@33bce1db
I/CAM_OneCamera1Opnr( 5857): Opening Camera: CameraId{Api2='0',Api1:0}
V/CAM_ActvCamDevTrckr( 5857): Tracking active camera: CameraId{Api2='0',Api1:0}
I/CameraManager( 5857): Using legacy camera HAL.
W/CameraService( 1566): CameraService::connect X (pid 5857) rejected (existing client).
W/Camera  ( 5857): An error occurred while connecting to camera: 0
D/CAM_StateMachine( 5857): Process event : com.android.camera.captureintent.event.EventOnOpenCameraFailed@1e9f1478
I/CAM_FocusRingView( 5857): Computing center via view bounds.
E/CAM_StateOpeningCamera( 5857): processOnCameraOpenFailure
D/CAM_StateMachine( 5857): Change state : com.android.camera.captureintent.state.StateOpeningCamera@33bce1db => com.android.camera.captureintent.state.StateFatal@ec87751
I/Keyboard.Facilitator( 2203): onFinishInput()
I/Keyboard.Facilitator( 2203): cancelLanguageModelFlush()
V/CAM_TexViewHelper( 5857): onLayoutChange
I/ActivityManager( 1898): Displayed com.google.android.GoogleCamera/com.android.camera.CaptureActivity: +387ms
E/mm-libcamera2( 1566): PROFILE HAL: stopPreview(): E: 1429363921.652549767
E/mm-camera( 1576): config_MSG_ID_STOP_ACK: streamon_mask is not clear. Should not call PP_Release_HW
E/CAM_FatalErrorHandler( 5857): Handling Camera Access Failure:
E/CAM_FatalErrorHandler( 5857): java.lang.Exception
E/CAM_FatalErrorHandler( 5857): 	at com.android.camera.FatalErrorHandlerImpl.onGenericCameraAccessFailure(FatalErrorHandlerImpl.java:82)
E/CAM_FatalErrorHandler( 5857): 	at com.android.camera.captureintent.state.StateFatal$1.run(StateFatal.java:53)
E/CAM_FatalErrorHandler( 5857): 	at android.os.Handler.handleCallback(Handler.java:739)
E/CAM_FatalErrorHandler( 5857): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/CAM_FatalErrorHandler( 5857): 	at android.os.Looper.loop(Looper.java:135)
E/CAM_FatalErrorHandler( 5857): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/CAM_FatalErrorHandler( 5857): 	at java.lang.reflect.Method.invoke(Native Method)
E/CAM_FatalErrorHandler( 5857): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/CAM_FatalErrorHandler( 5857): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/CAM_FatalErrorHandler( 5857): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/CAM_CameraUtil( 5857): Show fatal error dialog
E/mm-libcamera2( 1566): PROFILE HAL: stopPreview(): E: 1429363921.658165515
E/QCameraHWI( 1566): android::status_t android::QCameraHardwareInterface::setPreviewWindow(preview_stream_ops_t*):Received Setting NULL preview window
E/QCameraHWI( 1566): android::status_t android::QCameraHardwareInterface::setPreviewWindow(preview_stream_ops_t*): mPreviewWindow = 0x0x0, mStreamDisplay = 0x0xb798a820
W/QCameraHWI_Preview( 1566):  Setting NULL preview window 
I/CameraClient( 1566): Destroying camera 0
I/QCameraHWI( 1566): virtual android::QCameraHardwareInterface::~QCameraHardwareInterface() First stop the polling threads before deleting instances
E/mm-camera( 1576): config_shutdown_pp Camera not in streaming mode. Returning. 
E/mm-camera( 1576): vfe_ops_deinit: E
E/qcom_sensors_hal( 1898): hal_process_report_ind: Bad item quality: 11 
V/WindowManager( 1898): not Base app: Adding window Window{1ff3db9f u0 com.google.android.GoogleCamera/com.android.camera.CaptureActivity} at 15 of 21
D/CAM_FusedLocProvider( 5857): onConnected.
V/CAM_FusedLocProvider( 5857): starting location updates
D/AILOG   ( 7889): surfaceDestroyed

**Comment by javieriko** [comment]
can you give tutorial how to edit .apk from AI2 to java source code? i used eclipse anyway. I need add a live feed camera on my apps. Does it need new class? or just edit on .java? sorry i am totally newbies

**Comment by josmas** [comment]
@javieriko there is no ***easy*** way to turn an AI2 project into Java. You can modify the component directly (as in this pull request). The best way to get familiar with how to write or modify components is to follow the [documentation](http://appinventor.mit.edu/appinventor-sources/#documentation). [This document](https://docs.google.com/document/d/1xk9dMfczvjbbwD-wMsr-ffqkTlE3ga0ocCE1KOb2wvw/pub) is specific to components.

**Comment by javieriko** [comment]
so there no way to modify canvas component from .apk that compiled AI2? i try use apk studio but the class shown as .smali

**Comment by josmas** [comment]
@javieriko nope, no way to do it manually from a decompiled version unless you create specialised tools (which would probably be more difficult than writing a new Canvas component).

**Comment by kleffa** [comment]
@thequixotic what happens now with the extensions support? make this canvas as a extension is to much difficult?

**Comment by thequixotic** [comment]
@kleffa  I have tried making Canvas Camera Live Feed. The problem I had was with the way App Inventor scales its UI which gives me only a small window for camera instead of the entire canvas. Since I had to support it from API Level 4, it was not easily straight forward. I paused the project because I had other priority projects for App Inventor. I might get back to it soon.

**Comment by kleffa** [comment]
I think it works, I tried on my phone and yes saw the little preview, but if I rotate the phone get full screen.... Please don't surrender on this

**Comment by VASANTHP80P** [comment]
Can anyone give me the extension (.aix) file of canvas which you have changed. 
Please give me.


Thank You

**Comment by ewpatton** [comment]
@thequixotic I know this is rather old, but have you considered submitting a PR for this work (and are you still interested in working on it)? I'm looking for potential student projects, but if you still have it and are close to done I'd rather not duplicate work.

**Comment by kleffa** [comment]
https://puravidaapps.com/extensions.php

@ewpatton there is a extension for use the camera please check it
