### ISSUE TITLE
Videoplayer issues with API4

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#527]
It looks like the video sizing is wrong in Fixed mode with API4.   Responsive mode is better, but still a bit funny, I think.

But I also tried setting the player to fullscreen, and got an NPE crash.  All this needs to be looked into and we need to make sure the VideoPlayer works.

E/InputEventReceiver(22254): Exception dispatching input event.
E/MessageQueue-JNI(22254): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI(22254): java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.widget.MediaController$MediaPlayerControl.canPause()' on a null object reference
E/MessageQueue-JNI(22254): 	at android.widget.MediaController.disableUnsupportedButtons(MediaController.java:323)
E/MessageQueue-JNI(22254): 	at android.widget.MediaController.show(MediaController.java:352)

**Comment by halatmit** [comment]
also see issue #538

**Comment by halatmit** [comment]
This should have been fixed in #537
