### ISSUE TITLE
Installation Error: build.xml:17 The following error occurred while executing this line

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#861]
Hello

I'm getting BUILD FAILED when I execute the command `ant` in the installation. I created a log file to record all errors, and errors that I get are:

```
BUILD FAILED

D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\build.xml:17: The following error occurred while executing this line:
D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\build-common.xml:409: The following error occurred while executing this line:
D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\components\build.xml:122: The following error occurred while executing this line:
D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\build-common.xml:118: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:575)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:443)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:854)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\build-common.xml:409: The following error occurred while executing this line:
D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\components\build.xml:122: The following error occurred while executing this line:
D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\build-common.xml:118: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:575)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:443)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	... 17 more
Caused by: D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\components\build.xml:122: The following error occurred while executing this line:
D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\build-common.xml:118: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:575)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:399)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	... 29 more
Caused by: D:\Diego Barreiro Perez\GitHub\appinventor-sources\appinventor\build-common.xml:118: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1365)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1070)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	... 41 more
```

Anyone can help to fix that error?
Thanks

**Comment by ewpatton** [comment]
Do you have the java compiler (javac) on your path? From the stack trace it looks as though ant is unable to call javac. You can verify by typing `javac -version` from the command line.

**Comment by josmas** [comment]
There's a possibility that the spaces in your name (folder) are not agreeing with Java. In any case, please ask for help in the [open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev) if you still have issues.

**Comment by barreeeiroo** [comment]
Yes, it was the space in the path

Thanks

**Comment by pentanol2** [comment]
> Yes, it was the space in the path
> 
> Thanks

Could you explain this point, which path do you mean ?
